New requirement.txt (2021.10 ver)
ValueError: GRU(reset_after=False) is not compatible with GRU(reset_after=True)

need to down grade Tensorflow 1.15 and install all dependencies according to thins with this version.
This error is occurring probably because you are using TF 2.2 and in that version the tf.keras.layers.GRU is set to reset_after = false.
I tried changing it but it wasn't possible. 
Just ended up downgrading to TF 1.15 and install all other dependencies in sync with that version.

https://githubmemory.com/repo/rizkiarm/LipNet/issues/109